export const GET_USER_CLASSES = "GET_USER_CLASSES";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const GET_ALL_USER_AVAILABLE = "GET_ALL_USER_AVAILABLE";
export const GET_EDUCATOR_CLASSES = "GET_EDUCATOR_CLASSES";
